<h1>consultas</h1>
<div class="consultas">
    <li><a href="ubicacion.php">Ubicacion</a></li>
    <li><a href="usuarios.php">usuarios</a></li>
    <li><a href="fichas.php">Fichas</a></li>
    <li><a href="rep_u.php">Reporte por usuario</a></li>
    <li><a href="rep_f.php">Reporte por ficha</a></li>
    <li><a href="rep_a.php">Reporte ambiente</a></li>
</div>
<center><h1>Consulta Fichas (curso)</h1></center> <br>

<div class="form-row">
    <div class="form-group col-md-12">
        <div class="span10">
            <table class="table table-bordered table-striped table-hover table-condensed">
                <tr>
                    <th>ID</th>
                    <th>numero curso</th>
                    <th>Nombre curso</th>
                    <th>ID nivel curso</th>
                    <th>ID jornada curso</th>
                </tr>
                <tr>
                    <td>INF</td>
                    <td>INF</td>
                    <td>INF</td>
                    <td>INF</td>
                    <td>INF</td>
                </tr>
            </table>
        </div>
    </div>
</div>