<!--
* Autor: Camilo Figueroa ( Crivera )
* Vista: sección inicio.
*
-->

<center><h1>Resumen</h1></center> <br>
<h1>hola mundo eufhiuwfiu Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem fuga quibusdam eveniet veniam, accusantium optio animi delectus ex similique unde ullam saepe consequatur iure quam voluptatem recusandae repellat molestias iste?</h1>
<h1>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur quae ducimus quos minima nulla illum similique laborum, debitis velit quo provident eius et voluptates, fuga consequatur repudiandae, deleniti eligendi rem.</h1>
<h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa, quibusdam saepe. Ducimus corrupti tempora in, voluptas aliquid at eum impedit nostrum. Enim sunt laudantium aperiam accusantium, assumenda quisquam natus repellendus.</h1>
<br><br>
<h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore delectus aut omnis quidem, vitae repellendus ab natus asperiores, eius expedita saepe sequi quaerat. Tempora laboriosam obcaecati voluptatem vitae maiores quasi.</h1>
<h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quasi tempora, suscipit veniam adipisci illum inventore? Inventore praesentium vero asperiores quidem excepturi, itaque nulla quasi perspiciatis, quam nobis fugit provident eveniet.</h1>
<br><h1>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eaque explicabo sequi saepe. Alias ut dolore voluptates totam ad hic consectetur veniam, eligendi veritatis unde cupiditate vel aliquid eos similique voluptas?</h1>