<!--
* Autor: Camilo Figueroa ( Crivera )
* Vista: plantilla general.
-->

<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">
  <title>Control Covid_19</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Le styles -->
  <link href="../css/bootstrap.css" rel="stylesheet">

  <style>
    body {
      padding-top: 60px;
      /* 60px to make the container go all the way to the bottom of the topbar */
    }
  </style>
  <link href="../css/bootstrap-responsive.css" rel="stylesheet">

  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

  <!-- Le fav and touch icons -->
  <link rel="shortcut icon" href="https://getbootstrap.com/2.0.2/assets/ico/favicon.ico">
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="https://getbootstrap.com/2.0.2/assets/ico/apple-touch-icon-114-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="https://getbootstrap.com/2.0.2/assets/ico/apple-touch-icon-72-precomposed.png">
  <link rel="apple-touch-icon-precomposed" href="https://getbootstrap.com/2.0.2/assets/ico/apple-touch-icon-57-precomposed.png">
  <link rel="stylesheet" href="../css/pantalla.css">
</head>

<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Control covid_19</a><!-- Aquí el nombre del proyecto. -->
        <div class="nav-collapse collapse" style="height: 0px;">
          <ul class="nav">
            <!-- En esta parte se pueden editar y agregar más seccones al menú. HAy que cuidar la estructura. -->
            <li class="active"><a href="home.php">Home</a></li>
            <li><a href="reg_i.php">Ingreso</a></li>
            <li><a href="reg_u.php">Registrar usuarios</a></li>
            <li><a href="reg_c.php">Registrar Curso</a></li>
            <li><a href="reg_cl.php">Registrar Cliente</a></li>
            <li><a href="consulta.php">Consulta</a></li>  
            <li><a href="login.php">Cerrar seccion</a></li>
          </ul>
        </div>
        <!--/.nav-collapse -->
      </div>
    </div>
  </div>

  <div class="container">

    <?php include($seccion); ?>

  </div> <!-- /container -->

  <!-- Le javascript
    ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="../js/jquery.js"></script>
  <script src="../js/bootstrap-transition.js"></script>
  <script src="../js/bootstrap-alert.js"></script>
  <script src="../js/bootstrap-modal.js"></script>
  <script src="../js/bootstrap-dropdown.js"></script>
  <script src="../js/bootstrap-scrollspy.js"></script>
  <script src="../js/bootstrap-tab.js"></script>
  <script src="../js/bootstrap-tooltip.js"></script>
  <script src="../js/bootstrap-popover.js"></script>
  <script src="../js/bootstrap-button.js"></script>
  <script src="../js/bootstrap-collapse.js"></script>
  <script src="../js/bootstrap-carousel.js"></script>
  <script src="../js/bootstrap-typeahead.js"></script>



</body>

</html>