<br>
<form  class="ingreso">
<h1>Entrada</h1>

<input type="text" name="" id="" placeholder="Numero documento"> <br>
<select name="ubicacionn" id="ubicacionn">
    <option value="">Seleccione ubicacion</option>
</select>
</form>

<form class="salida">
    <h1>Salida</h1>
    <input type="text" name="" id="" placeholder="Numero documento"> <br>
    <input type="submit" value="Registrar">
</form>