<h1>Registro Clientes</h1> <br>
<form class="reg_cl">
    <input type="text" placeholder="Nombre cliente"> <br>
    <select name="documento" id="documento">
        <option value="">Tipo documento</option>
    </select> <br>
    <input type="number" placeholder="Numero documento"> <br>
    <input type="email" placeholder="Email"> <br>
    <input type="password" placeholder="Contraseña"> <br>
    <select name="rol" id="rol">
        <option value="">Seleccione el rol</option>
    </select> <br>
    <input type="number" placeholder="Telefono"> <br>
    <input type="submit" value="Registrar">
</form>