<h1>Registro de cursos</h1> <br>
<form class="reg_c">
<input type="number" placeholder="Numero de curso"> <br>
<input type="text" placeholder="Nombre del curso"> <br>
<select name="nivel_curso" id="nivel_curso">
<option value="">Nivel curso</option>
</select> <br>
<select name="jornada_curso" id="jornada_curso">
<option value="">jornada curso</option>
</select> <br>
<input type="button" value="REGISTRAR">
</form>