<h1>Registro Usuarios</h1> <br>

<form class="reg_u">
    <input type="text" placeholder="Nombre usuario"> <br>
    <select name="documento" id="documento">
        <option value="">Seleccione el documento</option>
    </select> <br>
    <input type="number" placeholder="Numero documento"> <br>
    <select name="rol" id="rol">
        <option value="">Seleccione el rol</option>
    </select> <br>
    <select name="estado" id="estado">
    <option value="">Seleccione el estado</option>
    </select> <br>
    <select name="curso" id="curso">
    <option value="">selecione el curso</option>
    </select> <br>
    <input type="submit" value="Registrar">
</form>