<h1>Consultas</h1>
<div class="consultas">
    <li><a href="ubicacion.php">Ubicacion</a></li>
    <li><a href="usuarios.php">usuarios</a></li>
    <li><a href="fichas.php">Fichas</a></li>
    <li><a href="rep_u.php">Reporte por usuario</a></li>
    <li><a href="rep_f.php">Reporte por ficha</a></li>
    <li><a href="rep_a.php">Reporte ambiente</a></li>
</div>

<h1>Reporte por ambiente</h1>
<form class="re_a">
    <select name="ambiente" id="ambiente">
        <option value="">Selecciona el ambiente</option>
    </select> <br>
    Fecha inicio <input type="date" > <br>
    Fecha fin <input type="date"> <br>
    <input type="submit" value="Enviar">
</form>