<h1>consultas</h1>
<div class="consultas">
    <li><a href="ubicacion.php">Ubicacion</a></li>
    <li><a href="usuarios.php">usuarios</a></li>
    <li><a href="fichas.php">Fichas</a></li>
    <li><a href="rep_u.php">Reporte por usuario</a></li>
    <li><a href="rep_f.php">Reporte por ficha</a></li>
    <li><a href="rep_a.php">Reporte ambiente</a></li>
</div>

<h1>aqui va el reporte por usuario</h1>